name: Update CNAME

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  update-cname:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Update CNAME
        run: |
          node updateCNAME.js

      - name: Commit and push changes
        run: |
          # 사용자 정보 설정
          git config --local user.email "202420505@eulji.ms.kr"
          git config --local user.name "GitHub Action"

          # CNAME 파일만 추가하여 커밋
          git add CNAME
          
          # CNAME 파일이 변경되었을 경우만 커밋
          if git diff --cached --quiet; then
            echo "No changes to CNAME file."
          else
            git commit -m "Update CNAME"
            git push
